using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KMDRecociliationApp.Domain.Entities.Configuration
{
    public class AssociationEntityTypeConfigurations
       : IEntityTypeConfiguration<Association>
    {
        public void Configure(EntityTypeBuilder<Association> builder)
        {
            List<Association> associations =
            [
                new Association
                {
                    Id = 1,
                    AssociationName = "PUNJAB NATIONAL BANK RETIREES ASSOCIATION - (MAHARASHTRA)",
                    OraganisationId = 1,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,


                },
                new Association
                {
                    Id = 2,
                    AssociationName = "UCO BANK RETIREES ASSOCIATION",
                    OraganisationId = 2,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 3,
                    AssociationName = "UNION BANK RETIRED EMPLOYEES ASSOCIATION GUJARAT",
                    OraganisationId = 3,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 4,
                    AssociationName = "UNITED BANK OF INDIA RETIREES WELFARE ASSOCIATION",
                    OraganisationId = 4,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 5,
                    AssociationName = "ALL INDIA SYNDICATE BANK RETIREES FEDERATION KARNATAKA STATE COMMITTEE",
                    OraganisationId = 5,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 6,
                    AssociationName = "ALL INDIA ALLAHABAD BANK RETIREES ASSOCIATION",
                    OraganisationId = 6,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 7,
                    AssociationName = "ALL INDIA PUNJAB & SIND BANK RETIRED OFFICERS ASSOCIATION",
                    OraganisationId = 7,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 8,
                    AssociationName = "BANK OF INDIA PENSIONERS AND RETIREES WELFARE ASSOCIATION (BOIPARA) CHANDIGARH",
                    OraganisationId = 8,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 9,
                    AssociationName = "CANARA BANK RETIRED OFFICERS ASSOCIATION",
                    OraganisationId = 9,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 10,
                    AssociationName = "FEDERAL BANK RETIREES ASSOCIATION AFFILIATED TO AKBRF",
                    OraganisationId = 10,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 11,
                    AssociationName = "SOUTH INDIAN BANK RETIRED STAFF ASSOCIATION",
                    OraganisationId = 11,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 12,
                    AssociationName = "VIJAYA BANK PENSIONERS AND RETIREES ASSOCIATION",
                    OraganisationId = 12,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 13,
                    AssociationName = "ANDHRA BANK RETIRED EMPLOYEES ASSOCIATION  (ABREA)",
                    OraganisationId = 13,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 14,
                    AssociationName = "CORPORATION BANK RETIRED OFFICERS ASSOCIATION",
                    OraganisationId = 14,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 15,
                    AssociationName = "BANK OF MAHARASHTRA RETIRED EMPLOYEES ORGANISATION",
                    OraganisationId = 15,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 16,
                    AssociationName = "A B RETIRED EMPLOYEES’ ASSOCIATION (WEST BENGAL)",
                    OraganisationId = 16,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 17,
                    AssociationName = "KERALA BANK RETIREES FEDERATION",
                    OraganisationId = 17,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 18,
                    AssociationName = "CENTRAL BANK RETIRED EMPLOYEES ASSOCIATION, MUMBAI",
                    OraganisationId = 18,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                //new Association
                //{
                //    Id = 19,
                //    AssociationName = "ALL INDIA DENA BANK RETIREES FEDERATION",
                //    OraganisationId = 19,
                //    Address1 = "address1",
                //    Address2 = "address2",
                //    City = "City",
                //    StateId = 1,
                //    PINCode = "12444",
                //    CountryId = 1,
                //    IsActive = true,
                //    CreatedAt = DateTime.UtcNow,
                //    CreatedBy = 0,
                //    UpdatedAt = DateTime.UtcNow,
                //    UpdatedBy = 0,
                //},
                new Association
                {
                    Id = 20,
                    AssociationName = "BANK OF BARODA RETIREES ASSOCIATION MAHARASHTRA",
                    OraganisationId = 20,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 21,
                    AssociationName = "ALL INDIA BANK RETIREE WELFARE ASSOCIATION",
                    OraganisationId = 21,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                //new Association
                //{
                //    Id = 22,
                //    AssociationName = "ALL INDIA BANK RETIREE WELFARE ASSOCIATION",
                //    OraganisationId = 21,
                //    Address1 = "address1",
                //    Address2 = "address2",
                //    City = "City",
                //    StateId = 1,
                //    PINCode = "12444",
                //    CountryId = 1,
                //    IsActive = true,
                //    CreatedAt = DateTime.UtcNow,
                //    CreatedBy = 0,
                //    UpdatedAt = DateTime.UtcNow,
                //    UpdatedBy = 0,
                //},
                new Association
                {
                    Id = 23,
                    AssociationName = "ALL INDIA CANARA BANK RETIREES FEDERATION",
                    OraganisationId = 9,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 24,
                    AssociationName = "ALL INDIA DENA BANK RETIREES FEDERATION",
                    OraganisationId = 19,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 25,
                    AssociationName = "ALL INDIA SYNDICATE BANK RETIREES FEDERATION MAHARASHTRA STATE COMMITTEE",
                    OraganisationId = 5,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 26,
                    AssociationName = "ALL INDIA UNION BANK RETIREES FEDERATION",
                    OraganisationId = 3,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 27,
                    AssociationName = "ANDHRA BANK PENSIONERS AND RETIREES FEDERATION",
                    OraganisationId = 13,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 28,
                    AssociationName = "BANK OF BARODA RETIRED OFFICERS ASSOCIATION",
                    OraganisationId = 20,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 29,
                    AssociationName = "BANK OF BARODA RETIRED OFFICERS' WELFARE ASSOCIATION",
                    OraganisationId = 20,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                //new Association
                //{
                //    Id = 30,
                //    AssociationName = "BANK OF BARODA RETIREES ASSOCIATION MAHARASHTRA",
                //    OraganisationId = 20,
                //    Address1 = "address1",
                //    Address2 = "address2",
                //    City = "City",
                //    StateId = 1,
                //    PINCode = "12444",
                //    CountryId = 1,
                //    IsActive = true,
                //    CreatedAt = DateTime.UtcNow,
                //    CreatedBy = 0,
                //    UpdatedAt = DateTime.UtcNow,
                //    UpdatedBy = 0,
                //},
                new Association
                {
                    Id = 31,
                    AssociationName = "BANK OF BARODA STAFF PENSIONERS ASSOCIATION GUJARAT, BARODA",
                    OraganisationId = 20,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 32,
                    AssociationName = "BANK OF INDIA PENSIONERS AND RETIREES ASSOCIATION (BOIPARA) GUJARAT",
                    OraganisationId = 8,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 33,
                    AssociationName = "BANK OF INDIA PENSIONERS' AND RETIREES' ASSOCIATION (BOIPARA), MUMBAI & GOA",
                    OraganisationId = 8,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 34,
                    AssociationName = "BANK OF INDIA RETIREES' ASSOCIATION (GUJARAT)",
                    OraganisationId = 8,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 35,
                    AssociationName = "BANK OF MAHARASHTRA RETIREES ASSOCIATION",
                    OraganisationId = 15,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                //new Association
                //{
                //    Id = 36,
                //    AssociationName = "CENTRAL BANK RETIRED EMPLOYEES ASSOCIATION, MUMBAI",
                //    OraganisationId = 18,
                //    Address1 = "address1",
                //    Address2 = "address2",
                //    City = "City",
                //    StateId = 1,
                //    PINCode = "12444",
                //    CountryId = 1,
                //    IsActive = true,
                //    CreatedAt = DateTime.UtcNow,
                //    CreatedBy = 0,
                //    UpdatedAt = DateTime.UtcNow,
                //    UpdatedBy = 0,
                //},
                new Association
                {
                    Id = 37,
                    AssociationName = "DENA BANK PENSIONERS AND RETIREES ASSOCIATION",
                    OraganisationId = 19,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 38,
                    AssociationName = "DENA BANK RETIRED EMPLOYEES WELFARE ASSOCIATION (SURAT)",
                    OraganisationId = 19,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 39,
                    AssociationName = "INDIAN BANK RETIRED STAFF ASSOCIATION GUJARAT",
                    OraganisationId = 22,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 40,
                    AssociationName = "INDIAN BANK RETIREES ASSOCIATION",
                    OraganisationId = 22,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 41,
                    AssociationName = "PUNJAB NATIONAL BANK RETIREES ASSOCIATION (GUJARAT)",
                    OraganisationId = 1,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 42,
                    AssociationName = "PUNJAB NATIONAL BANK SRAMIK UNION",
                    OraganisationId = 1,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 43,
                    AssociationName = "UCO BANK NIVRUT PARIVAR (GUJARAT UNIT)",
                    OraganisationId = 2,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 44,
                    AssociationName = "UCO BANK RETIRED EMPLOYEES ASSOCIATION (SURAT)",
                    OraganisationId = 2,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 45,
                    AssociationName = "UNITED FORUM OF BANK RETIREES",
                    OraganisationId = 21,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 46,
                    AssociationName = "ALL INDIA PNB RETIRED OFFICERS ASSOCIATION (REGD.)",
                    OraganisationId = 1,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 47,
                    AssociationName = "ALL INDIA PUNJAB NATIONAL BANK PENSIONERS AND RETIREES ASSOCIATION  (AIPNBPRA) (AFFILIATED TO AIPNBOA & AIBPARC)",
                    OraganisationId = 1,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 48,
                    AssociationName = "ALL INDIA PUNJAB NATIONAL BANK RETIREES FEDERATION",
                    OraganisationId = 1,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 49,
                    AssociationName = "CATHOLIC SYRIAN BANK RETIREES ASSOCIATION",
                    OraganisationId = 23,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 50,
                    AssociationName = "CENTRAL BANK RETIRED EMPLOYEES ASSOCIATION - PUNE ZONE",
                    OraganisationId = 18,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 51,
                    AssociationName = "FEDERATION OF BANK OF INDIA RETIREES ASSOCIATION",
                    OraganisationId = 8,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 52,
                    AssociationName = "VIJAYA BANK RETIREES ASSOCIATION (REGD)",
                    OraganisationId = 12,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 53,
                    AssociationName = "FEDERAL BANK RETIRED OFFICERS FORUM",
                    OraganisationId = 10,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                },
                new Association
                {
                    Id = 54,
                    AssociationName = "BANK OF INDIA PENSIONERS AND RETIREES ASSOCIATION (BOIPARA - DELHI)",
                    OraganisationId = 8,
                    Address1 = "address1",
                    Address2 = "address2",
                    City = "City",
                    StateId = 1,
                    PINCode = "12444",
                    CountryId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 0,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 0,
                }
            ];
            builder
              .HasOne(a => a.Organisation)
              .WithMany(o => o.Association)
              .HasForeignKey(a => a.OraganisationId);

            builder.Property(p => p.Id).IsRequired().UseIdentityColumn();
            builder.Property(p => p.AssociationName).IsRequired()
                .HasColumnType("Varchar").HasMaxLength(200);
            builder.Property(p => p.IsActive).HasDefaultValue(true);
            builder.Property (p => p.CreatedAt).HasDefaultValue(DateTime.Now);
            builder.Property(p => p.UpdatedAt).HasDefaultValue(DateTime.Now);
            

            //default data
           // builder.HasData(associations);

        }
    }

}
