using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KMDRecociliationApp.Domain.Entities.Configuration
{
    public class AssociationBankDetailsEntityTypeConfigurations
      : IEntityTypeConfiguration<AssociationBankDetails>
    {
        public void Configure(EntityTypeBuilder<AssociationBankDetails> builder)
        {
            List<AssociationBankDetails> associationsbank =
            [
                new AssociationBankDetails
                {
                    Id = 1,
                    BankName = "PUNJAB NATIONAL BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 1,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,


                },
                new AssociationBankDetails
                {
                    Id = 2,
                    BankName = "UCO BANK ",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 2,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 3,
                    BankName = "UNION BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 3,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 4,
                    BankName = "UNITED BANK OF INDIA ",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 4,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 5,
                    BankName = "SYNDICATE BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 5,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 6,
                    BankName = "ALLAHABAD BANK ",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 6,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 7,
                    BankName = "PUNJAB & SIND BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 7,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 8,
                    BankName = "BANK OF INDIA",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 8,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 9,
                    BankName = "CANARA BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 9,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 10,
                    BankName = "FEDERAL BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 10,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 11,
                    BankName = "SOUTH INDIAN BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 11,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 12,
                    BankName = "VIJAYA BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 12,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 13,
                    BankName = "ANDHRA BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 13,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 14,
                    BankName = "CORPORATION BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 14,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 15,
                    BankName = "BANK OF MAHARASHTRA",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 15,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 16,
                    BankName = "A B",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 16,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 17,
                    BankName = "KERALA BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 17,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 18,
                    BankName = "CENTRAL BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 18,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 19,
                    BankName = "DENA BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 19,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 20,
                    BankName = "BANK OF BARODA",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 20,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 21,
                    BankName = "BANK OF BARODA",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 21,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 22,
                    BankName = "INDIA BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 22,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,


                },
                new AssociationBankDetails
                {
                    Id = 23,
                    BankName = "CANARA BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 23,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 24,
                    BankName = "INDIA DENA BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 24,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 25,
                    BankName = "INDIA SYNDICATE BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 25,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 26,
                    BankName = "INDIA UNION BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 26,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 27,
                    BankName = "ANDHRA BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 27,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 28,
                    BankName = "BANK OF BARODA",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 28,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 29,
                    BankName = "BANK OF BARODA",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 29,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 30,
                    BankName = "BANK OF BARODA",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 30,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 31,
                    BankName = "BANK OF BARODA",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 31,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 32,
                    BankName = "BANK OF INDIA",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 32,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 33,
                    BankName = "BANK OF INDIA",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 33,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 34,
                    BankName = "BANK OF INDIA",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 34,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 35,
                    BankName = "BANK OF MAHARASHTRA",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 35,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 36,
                    BankName = "CENTRAL BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 36,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 37,
                    BankName = "DENA BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 37,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 38,
                    BankName = "DENA BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 38,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 39,
                    BankName = "INDIAN BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 39,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 40,
                    BankName = "INDIAN BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 40,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 41,
                    BankName = "PUNJAB NATIONAL BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 41,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 42,
                    BankName = "PUNJAB NATIONAL BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 42,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 43,
                    BankName = "UCO BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 43,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 44,
                    BankName = "UCO BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 44,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 45,
                    BankName = "BANK OF INDIA",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 45,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 46,
                    BankName = "INDIA PNB",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 46,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 47,
                    BankName = "INDIA PUNJAB NATIONAL BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 47,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 48,
                    BankName = "INDIA PUNJAB NATIONAL BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 48,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 49,
                    BankName = "CATHOLIC SYRIAN BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 49,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 50,
                    BankName = "CENTRAL BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 50,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 51,
                    BankName = "FEDERATION OF BANK OF INDIA",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 51,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 52,
                    BankName = "VIJAYA BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 52,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 53,
                    BankName = "FEDERAL BANK",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 53,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                new AssociationBankDetails
                {
                    Id = 54,
                    BankName = "BANK OF INDIA",
                    BranchName = "branch name",
                    AccountName = "123456789",
                    AccountNumber = "12345467",
                    IFSCCode = "12345",
                    MICRCode = "13454",
                    AssociationId = 54,
                    IsActive = true,
                    CreatedAt = DateTime.UtcNow,
                    CreatedBy = 2,
                    UpdatedAt = DateTime.UtcNow,
                    UpdatedBy = 2,
                },
                
            ];

            builder.Property(p => p.Id).IsRequired().UseIdentityColumn();
            builder.Property(p => p.IsActive).HasDefaultValue(true);
            builder.Property(p => p.IsActive).HasDefaultValue(true);
            builder.Property(p => p.CreatedAt).HasDefaultValue(DateTime.Now);
            builder.Property(p => p.UpdatedAt).HasDefaultValue(DateTime.Now);


            //default data
            //builder.HasData(associationsbank);

        }
    }

}
